### PR TITLE
Make DS Project tests independent

### PR DESCRIPTION
**Pull request by bdattoma**
This PR wants to address the issue of having the DS Project tests dependent on each other which makes difficult moving the tests in and out of a Quality Gate.

**How**
The way to achieve some level of indendence implemented by this PR is the following:
1. having one common DS project created as part of Suite Setup
2. every test which needs a resource, must create it as part of test setup and delete it in the test teardown
     - this was to me a bit concerning bcos it would increase the total duration of testing (a workbench takes around 40-50s to be up and running). However I tried mitigating this issue by merging some smaller test cases together.
     - time impact is going to be assessed as part of the PR testing

The PR required many changes and I'll try to test as much as I can the impacted Suites

**Merged test cases**
- ODS-1817,ODS-1815,ODS-1813,ODS-1784
- ODS-1823, ODS-1818
_The merge happened only at code repo level, not in Polarion_: the new cumulative test case reports all the aggregated test IDs as RF Tags

### CODE REVIEW

**Comment by bdattoma** [comment]
PR Validation:
1) `rhods-ci-pr-test/2039` DS project Suite SUCCESS. "Edit" suite FAILED -> fixed and will re-test
2) ..

**Review by FedeAlonso — APPROVED** [review]
There are a bunch of fixes (indentations, RETURN, etc) that can be easily fixed following the alerts.
LGTM

**Review by jgarciao — APPROVED** [review]
There is some commented code that could be removed in this or a follow-up PR. Otherwise LGTM

**Comment by bdattoma** [comment]
> There is some commented code that could be removed in this or a follow-up PR. Otherwise LGTM

yeah, sorry for that. I originally left some of them bcos I wasn't sure if they were still needed for test stability. I will remove commented in code in a next PR

**Pull request merged**
