### PR TITLE
Update to Robot Framework 6(.1.1)

### PR DESCRIPTION
**Pull request by lugi0**

### CODE REVIEW

**Comment by jgarciao** [comment]
Can you update also these dev dependencies?
```
[tool.poetry.group.dev.dependencies]
robotframework-lsp = ">=1.11.0"
robotframework-robocop = "^4.1.0"
robotframework-tidy = "^4.5.0"
```

**Comment by lugi0** [comment]
@jgarciao is there a specific reason for doing that? What version(s) do you need?

**Comment by jgarciao** [comment]
> @jgarciao is there a specific reason for doing that? What version(s) do you need?

For the 3 of them I would like to have the latest version available at this time (the ones in the example)

**Review by diegolovison — APPROVED** [review]
@lugi0 please rebase

**Comment by jstourac** [comment]
JFTR: superseded by #923

**Pull request closed without merging**
