### PR TITLE
Moved fetch cluster type to RHOSi.resources and assign correct subscr…

### PR DESCRIPTION
**Pull request by asanzgom**
…iption name for managed cluster

### CODE REVIEW

**Review by CFSNM — CHANGES_REQUESTED** [review]
@asanzgom I tried this PR with a managed cluster and there are some failures in the tests. You can check rhoai-test-flow 1732 job for more information

**Comment by asanzgom** [comment]
> @asanzgom I tried this PR with a managed cluster and there are some failures in the tests. You can check rhoai-test-flow 1732 job for more information

yes @CFSNM still doing some changes

**Comment by asanzgom** [comment]
rhoai-test-flow/1886 succeded

**Review by CFSNM — DISMISSED** [review]

**Review by MarianMacik — COMMENTED** [review]
One improvement, otherwise looks good.

**Comment by asanzgom** [comment]
passed successfully for Self-Managed on rhoai-test-flow/1906/

**Review by MarianMacik — APPROVED** [review]
LGTM!

**Review by CFSNM — APPROVED** [review]
lets backport it to releases/2.16.0 branch

**Pull request merged**
