### PR TITLE
Add new NB for GPU testing of PyTorch

### PR DESCRIPTION
**Pull request by lugi0**
Signed-off-by: Luca Giorgi <lgiorgi@redhat.com>

### CODE REVIEW

**Review by tarukumar — APPROVED** [review]
LGTM

**Review by jgarciao — COMMENTED** [review]
Could you transfer the whole repo to https://github.com/redhat-rhods-qe?

Additionally (if you want) it could be renamed to https://github.com/redhat-rhods-qe/ods-ci-notebook-benchmark

I think repos can be transferred from the Settings section: https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository

**Comment by lugi0** [comment]
I can do that, but first we need to refactor all TCs that pull those notebooks, otherwise they will be broken

**Comment by lugi0** [comment]
@jgarciao should we merge first or transfer the repo first?

**Comment by jgarciao** [comment]
I think transfering can take a few minutes so let's do the transfer first

**Comment by jgarciao** [comment]
Could you do also these repos?
- https://github.com/lugi0/minimal-nb-image-test
- https://github.com/lugi0/clustering-notebook
If this is a lot of work I'm fine doing it in next sprint and now just add the notebook as it was your first commit

**Review by jgarciao — APPROVED** [review]
lgtm (we'll do the repo transfer in the future)

**Comment by lugi0** [comment]
Reverting last change. We can merge as is and transfer all repos at the beginning of next sprint as suggested by @jgarciao

**Review by bdattoma — APPROVED** [review]

**Pull request merged**
