### PR TITLE
(2.13 backport) RHOAIENG-12833 - Validate Image Pull Path Is From registry.redhat.io

### PR DESCRIPTION
**Pull request by mattmahoneyrh**
The purpose of this enhancement is to check that the Component Deployment image pull path is from registry.redhat.io, when expected to be so.

Note: kserve-controller-manager is an exception which is pulled from quay.io, thus not validated for pull path registry.redhat.io

### CODE REVIEW

**Comment by CFSNM** [comment]
@mattmahoneyrh lets rebase the 2.13 branch and solve the conflicts before reviewing, please

**Comment by jstourac** [comment]
> @mattmahoneyrh lets rebase the 2.13 branch and solve the conflicts before reviewing, please

Also, please - retarget this PR to appropriate `releases/2.13.0` branch instead of `master`.

**Comment by mattmahoneyrh** [comment]
This branch is not correct. Will close this PR, then redo fresh.

**Comment by jstourac** [comment]
This was closed in favor of #1827.

**Pull request closed without merging**
