### PR TITLE
Add support to create DSC without any conditon for rhods24

### PR DESCRIPTION
**Pull request by tarukumar**
From RHODS 2.4 all the channel will have v2 operator. In this PR we are removing the condition to apply DSC and keep it as a default. 

PS: We can also remove the condition for component verification using update channel but for now the above changes should work for RHODS 2.4

### CODE REVIEW

**Review by jstourac — DISMISSED** [review]

**Comment by jstourac** [comment]
LGTM, any successful run to prove this is working as expected?

Also, I suppose this needs to wait for merge until 1.34 branch is created, right?

**Comment by tarukumar** [comment]
> LGTM, any successful run to prove this is working as expected?
> 
> Also, I suppose this needs to wait for merge until 1.34 branch is created, right?

yes...and one run has been successful already.

**Comment by jstourac** [comment]
@tarukumar looks like this change needs to be incorporated https://github.com/red-hat-data-services/ods-ci/commit/3dcde980e3f446ff240d3b13a454515f75291c03 - test run here `rhods-smoke/3819`. Please add, thank you.

**Review by aloganat — APPROVED** [review]
lgtm

**Review by mwaykole — APPROVED** [review]

**Pull request merged**
