### PR TITLE
Revert "add RESOURCE_EDIT_BTN variable and check for it (#1865)"

### PR DESCRIPTION
**Pull request by FedeAlonso**
This reverts commit 13aebede9ae805176778d5ff9766537a24648bb9.

### CODE REVIEW

**Comment by jstourac** [comment]
For the context - the original PR was merged [slightly pre-maturely maybe](https://github.com/red-hat-data-services/ods-ci/pull/1865#issuecomment-2379240580). Thus this revert.

In [this comment](https://github.com/red-hat-data-services/ods-ci/pull/1865#issuecomment-2379362508) it seems that the downstream should be there already, but maybe not. Will leave the investigation on you, guys, but will approve just in case this needs to be merged in a hurry.

**Review by jstourac — APPROVED** [review]
approved, but please read my comment above for the full picture

**Comment by rnetser** [comment]
@FedeAlonso this breaks 2.13. Can it be merged?

**Comment by jstourac** [comment]
> @FedeAlonso the original change breaks 2.13. Can it be merged?

It did on Friday (reportedly), but based on the run from today (very briefly scanned through), I don't see such problem in the log? `job/rhoai/job/autotrigger-smoke/319/robot/report/log.html`; `odh-operator-bundle-container-v2.14.0-32`; IIIB: 827794

There are other xpath changes required though, true.

**Pull request closed without merging**
