### PR TITLE
Checking for oauth container ODS-355

### PR DESCRIPTION
**Pull request by pranavsuryaw**
Signed-off-by: Pranav Suryawanshi <prsuryaw@redhat.com>

### CODE REVIEW

**Comment by bdattoma** [comment]
it seems good. Only one doubt about using `Search Pods` (which should return kw rather than `Get Pods`. Please test it on jenkins :)

**Comment by pranavsuryaw** [comment]
Result : Passed
https://opendatascience-jenkins-csb-rhods.apps.ocp-c1.prod.psi.redhat.com/job/rhods-ci-pr-test/920/console

**Review by bdattoma — APPROVED** [review]

**Review by lugi0 — APPROVED** [review]
lgtm

**Comment by bdattoma** [comment]
@pranavsuryaw PR is merged. Please update polarion accordingly

**Comment by pranavsuryaw** [comment]
Updated

**Pull request merged**
