### PR TITLE
add resource import to avoid "Keyword Not Found"

### PR DESCRIPTION
**Pull request by bdattoma**
to fix the issue raised in this Smoke: https://opendatascience-jenkins-csb-rhods.apps.ocp-c1.prod.psi.redhat.com/job/rhods-smoke/256/TestReport/

### CODE REVIEW

**Review by lugi0 — APPROVED** [review]

**Review by jgarciao — APPROVED** [review]
LGTM

**Comment by bdattoma** [comment]
If you agree @lugi0 @jgarciao  I would close this PR in favour of https://github.com/red-hat-data-services/ods-ci/pull/145 which already includes this change. Is that okay?

**Comment by lugi0** [comment]
Since this fixes an issue in smoke I'd say it should be merged ASAP, probably easier to merge this quickly and rebase #145

**Comment by bdattoma** [comment]
> Since this fixes an issue in smoke I'd say it should be merged ASAP, probably easier to merge this quickly and rebase #145
I'm running smoke for #145 so the change under this PR will be tested too

**Comment by bdattoma** [comment]
Closing this in favor of #145  (merged)

**Pull request closed without merging**
