### PR TITLE
Properly set multiline custom CA Bundle

### PR DESCRIPTION
**Pull request by apodhrad**
This was already merged to the master branch but we need it also for 2.8 smoke tests

* master #1433
* 2.9 branch #1439

### CODE REVIEW

**Comment by jstourac** [comment]
Has this been tested with 2.8 branch?

**Comment by apodhrad** [comment]
No :(
Let's verify it on 2.8.2

**Comment by jstourac** [comment]
You know, the changes LGTM and shouldn't break anything hopefully. But I'm not even sure we truly need it for 2.8 - are the tests that this fixes actually present in this branch and are being run? I haven't checked personally, so asking :slightly_smiling_face:

**Comment by apodhrad** [comment]
They are part of the smoke tests, so the goal here is to make at least the smoke tests as stable as possible and reduce the work related to failure investigations for 2.8.3, 2.8.4 , ... for several months

**Review by mattmahoneyrh — APPROVED** [review]

**Comment by apodhrad** [comment]
In 2.8 we would need to add also other commits

**Comment by jstourac** [comment]
@apodhrad for 2.8, the smokes are basically always green in connected env. Do I understand correctly that you see these tests failing in disconnected?

**Comment by apodhrad** [comment]
> @apodhrad for 2.8, the smokes are basically always green in connected env. Do I understand correctly that you see these tests failing in disconnected?

worse, these tests are green but they delete the ca bundles which could cause other failures, so it depends on the order of executed tests

**Comment by apodhrad** [comment]
@jstourac @mattmahoneyrh I have added changes related to restoring the ca bundles + the my recent change.
I have tested that with 2.8.2.GA where the tests are green and the CA bundles were properly restored.

**Pull request merged**
