### PR TITLE
[Fix] BYON images changes

### PR DESCRIPTION
**Pull request by mwaykole**
product bug dev will fix it 

Signed-off-by: mwaykole <mwaykole@redhat.com>

### CODE REVIEW

**Review by aloganat — APPROVED** [review]
lgtm

**Comment by jgarciao** [comment]
@mwaykole If this change is due to a bug in RHODS I think you should leave the code as it was and add to the failing tests the ProductBug tag add the bug ids in the [Documentation] section (see example in the style guide)

**Comment by jgarciao** [comment]
I believe this PR is not needed anymore, as is it fixed in the product

**Comment by mwaykole** [comment]
okay  form closing this PR

**Pull request closed without merging**
