### PR TITLE
Model Registry e2e UI test + breaking ui changes

### PR DESCRIPTION
**Pull request by lugi0**

### CODE REVIEW

**Comment by lugi0** [comment]
Verified in rhoai-test-flow/657

**Comment by lugi0** [comment]
@jstourac adding you as a reviewer as well because of some changes to `ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource` and `ods_ci/tests/Resources/Page/ODH/JupyterHub/JupyterLabLauncher.robot`

**Review by CFSNM — APPROVED** [review]
LGTM!

**Review by jstourac — COMMENTED** [review]
/lgtm

thank you for the changes!

**Pull request merged**
