### PR TITLE
[Draft]Add authorino operator only for odh nightly

### PR DESCRIPTION
**Pull request by aloganat**

### CODE REVIEW

**Review by jiridanek — APPROVED** [review]

**Comment by jstourac** [comment]
I'm not sure whether we sill need and want this? :thinking:

**Comment by jiridanek** [comment]
Imo yes, authorino is going to come sooner or later, and nobody removed it from upstream odh, as far as I know.

**Comment by jstourac** [comment]
> Imo yes, authorino is going to come sooner or later, and nobody removed it from upstream odh, as far as I know.

Yeah, but this PR is to install it against ODH-nighly only, which was okay up to last week for RHOAI, but then plan changed, so I'm not sure whether this is still needed :slightly_smiling_face:

**Comment by jstourac** [comment]
Just for the reference - Red Hat Authorino is now available on OCP4.15 - https://issues.redhat.com/browse/RHOAIENG-4710.

**Pull request closed without merging**
