### PR TITLE
Update must-gather image tag according to RHODS-8050

### PR DESCRIPTION
**Pull request by jgarciao**
New image is quay.io/modh/must-gather:stable. More info at https://github.com/red-hat-data-services/must-gather/pull/6/files

### CODE REVIEW

**Review by DharmitD — COMMENTED** [review]
/lgtm

**Review by bdattoma — APPROVED** [review]

**Review by tarukumar — APPROVED** [review]
/lgtm

**Review by tarukumar — APPROVED** [review]
/lgtm

**Review by tarukumar — APPROVED** [review]
/lgtm

**Pull request merged**
