### PR TITLE
Added Python model gRPC protocol test on triton for Kserve

### PR DESCRIPTION
**Pull request by Raghul-M**

### CODE REVIEW

**Comment by Raghul-M** [comment]
Verified with Jenkins Build 1574

**Comment by bdattoma** [comment]
> @bdattoma Testing it against 2.15

please test against 2.16 instead

**Comment by Raghul-M** [comment]
Verified with Jenkins Build 1590 ( in RHOAI 2.16)

**Comment by bdattoma** [comment]
> @bdattoma I tested it against RHOAI 2.16, and due to the changes in the UI, it's failing.

then in order to be merged into `master` branch, it must work against 2.16

**Comment by Raghul-M** [comment]
Verified with Jenkins Build 1868

**Review by bdattoma — APPROVED** [review]

**Review by tarukumar — APPROVED** [review]

**Pull request merged**
