### PR TITLE
Make pvc alert test teardown more robust

### PR DESCRIPTION
**Pull request by jgarciao**
Signed-off-by: Jorge Garcia Oncins <jgarciao@redhat.com>

### CODE REVIEW

**Comment by jgarciao** [comment]
I's being tested here: https://opendatascience-jenkins-csb-rhods.apps.ocp-c1.prod.psi.redhat.com/job/rhods-tier2/22/

**Comment by bdattoma** [comment]
mmh wouldn't be possible to use `Fix Spawner Status` instead of a custom teardown for this TC? They might be equivalent

**Comment by jgarciao** [comment]
This test has a custom teardown because it was super tricky to get teardown work properly, specially when PVC is near 100%. I prefer not to touch it, at least now.

Test finished successfully  https://opendatascience-jenkins-csb-rhods.apps.ocp-c1.prod.psi.redhat.com/job/rhods-tier2/22/

**Review by bdattoma — APPROVED** [review]

**Comment by bdattoma** [comment]
lgtm

**Review by tarukumar — APPROVED** [review]
LGTM

**Pull request merged**
