### PR TITLE
add three additional test users to test-variables for automating ODS-293

### PR DESCRIPTION
**Pull request by bdattoma**
to be merged for allowing #208 to run
Signed-off-by: bdattoma <bdattoma@redhat.com>

### CODE REVIEW

**Comment by lugi0** [comment]
Considering we already know the format of the usernames created in the cluster (i.e ldap-user/adminN), is this actually needed?

**Comment by bdattoma** [comment]
> Considering we already know the format of the usernames created in the cluster (i.e ldap-user/adminN), is this actually needed?

I think so, IMO we shouldn't mention anywhere in the code the usernames. Besides, if we change naming logic, this way would be easier to update the code.

**Review by lugi0 — APPROVED** [review]
lgtm

**Review by jgarciao — APPROVED** [review]
LGTM

**Pull request merged**
