### PR TITLE
Updating run.sh file permissions

### PR DESCRIPTION
**Pull request by omrirh**
- The `build/run.sh` script is being used for managed services integration team's [RHODS integration](https://issues.redhat.com/browse/MSINTEROP-322) testsuite.
- Following a permission error when running this testsuite within [openshift-ci (line 63)](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/37677/rehearse-37677-periodic-ci-CSPI-QE-MSI-rhods-rhods-tests/1650161721978916864), we are asking to modify this script's file permissions from 644 to 755 and update the latest image tag.
- [RHODS onboarding to openshift-ci PR](https://github.com/openshift/release/pull/37677)

### CODE REVIEW

**Comment by bdattoma** [comment]
@omrirh have you tried running the openshift-ci job with the change from this PR?

**Comment by tarukumar** [comment]
@bdattoma I think we need to create a new container image with updated permission, for them to validate it right? Or are you asking to validate it from local container ?

**Comment by omrirh** [comment]
Hi @bdattoma @tarukumar ,
I've updated the permissions config for `build/run.sh` in the Dockerfile as well.
Would be great if you can create a test image tag for ods-ci so I could target it in openshift-ci
and see if it resolves our permissions issue.
Thanks! :)

**Pull request closed without merging**
