### PR TITLE
Skip pre-req install by default in the KServe test suite

### PR DESCRIPTION
**Pull request by bdattoma**
To avoid conflicts after https://github.com/red-hat-data-services/ods-ci/pull/1039 got merged, we should skip installing the pre-requirements in the KServe suite. 
The suite can still install them by setting `SKIP_PREREQS_INSTALL` variable to `False` at runtime

### CODE REVIEW

**Review by aloganat — APPROVED** [review]

**Comment by jstourac** [comment]
Isn't it possible to check whether these prerequisities are installed already? :thinking:

**Review by lugi0 — APPROVED** [review]

**Comment by bdattoma** [comment]
> Isn't it possible to check whether these prerequisities are installed already? 🤔

yes it's possible. We could implement a check in future PRs, it would take time we don't have now and the benefit would be minimal

**Comment by jstourac** [comment]
> yes it's possible. We could implement a check in future PRs, it would take time we don't have now and the benefit would be minimal

Maybe I'm missing something but I don't agree that the benefit would be minimal :slightly_smiling_face:  Anyway, I agree that we need this fast.

**Review by jstourac — APPROVED** [review]

**Comment by bdattoma** [comment]
> > yes it's possible. We could implement a check in future PRs, it would take time we don't have now and the benefit would be minimal
> 
> Maybe I'm missing something but I don't agree that the benefit would be minimal 🙂 Anyway, I agree that we need this fast.

we can talk offline

**Pull request merged**
