### PR TITLE
RHOAIENG-7298 - New DSC Component Dashboard and Datasciencepipelines Test Cases

### PR DESCRIPTION
**Pull request by mattmahoneyrh**
Adding DSC component Dashboard and Datasciencepipelines Test Cases. 

Extended resource check timeouts.

Improved pod ready check to include all pods with given label-selector.

### CODE REVIEW

**Comment by mattmahoneyrh** [comment]
Jenkins runs passed RHOAI 2.10 and ODH 2.12.1.

**Review by zdtsw — APPROVED** [review]

**Review by CFSNM — APPROVED** [review]
LGTM

**Comment by bdattoma** [comment]
lgtm. Question: what would happen when setting a component to Unmanaged when the component is not supposed to accept that value? 
@zdtsw is there a unit testing covering this case maybe?

**Review by bdattoma — APPROVED** [review]

**Comment by zdtsw** [comment]
> lgtm. Question: what would happen when setting a component to Unmanaged when the component is not supposed to accept that value? @zdtsw is there a unit testing covering this case maybe?

I do not think we enabled on component level user can set value to unmanaged, only the serverless servicemesh and trustcca  support this value. 
in short, user wont allowed to set it, get rejected by patch or create DSC CR with it

**Comment by mattmahoneyrh** [comment]
@bdattoma  an attempt to set the managementState to an unsupported value would be disallowed/fail, with a message indicating such as well as the supported values.

Can add negative tests. Good suggestion.

**Pull request merged**
