### PR TITLE
Fix flacky metrics test failing with "no datapoints found"

### PR DESCRIPTION
**Pull request by jgarciao**

### CODE REVIEW

**Comment by jgarciao** [comment]
Testing this right now here: https://opendatascience-jenkins-csb-rhods.apps.ocp4.prod.psi.redhat.com/job/rhods-ci-pr-test/121

**Comment by jgarciao** [comment]
Prometheus pod wan't working properly and the previous test failed. Testing again here after restarting the worker nodes at modh-qe-7: https://opendatascience-jenkins-csb-rhods.apps.ocp4.prod.psi.redhat.com/job/rhods-ci-pr-test/123

**Comment by jgarciao** [comment]
It failed again because of prometheus and some jupyterhub pods not working. Testing again here:  https://opendatascience-jenkins-csb-rhods.apps.ocp4.prod.psi.redhat.com/job/rhods-ci-pr-test/124

**Comment by jgarciao** [comment]
Testing again here in a new OSD cluster: https://opendatascience-jenkins-csb-rhods.apps.ocp4.prod.psi.redhat.com/job/rhods-sanity/198/

**Comment by jgarciao** [comment]
https://opendatascience-jenkins-csb-rhods.apps.ocp4.prod.psi.redhat.com/job/rhods-ci-pr-test/134/console

All billing tests passed in a new OSD cluster. I believe they didn't pass before because of JuyterHub HA issues

@vasukulkarni I think this can be merged now


```
==============================================================================
Tests                                                                         
==============================================================================
Tests.Monitor And Manage                                                      
==============================================================================
Tests.Monitor And Manage.Metrics                                              
==============================================================================
Tests.Monitor And Manage.Metrics.Billing Metrics                              
==============================================================================

Verify OpenShift Monitoring results are correct when running undef... | PASS |
------------------------------------------------------------------------------

Test Billing Metric (notebook cpu usage) on OpenShift Monitoring      | PASS |
------------------------------------------------------------------------------
Tests.Monitor And Manage.Metrics.Billing Metrics                      | PASS |
2 tests, 2 passed, 0 failed
==============================================================================
Tests.Monitor And Manage.Metrics                                      | PASS |
2 tests, 2 passed, 0 failed
```

**Review by vasukulkarni — APPROVED** [review]

**Pull request merged**
