### PR TITLE
Verify PostgreSQL Is Not Deployed When AWS RDS Is Enabled

### PR DESCRIPTION
**Pull request by pablofelix**
Signed-off-by: Pablo Félix Estévez Pico <pestevez@redhat.com>

### CODE REVIEW

**Comment by pablofelix** [comment]
https://opendatascience-jenkins-csb-rhods.apps.ocp-c1.prod.psi.redhat.com/job/rhods-ci-pr-test/985/

**Review by mwaykole — APPROVED** [review]
LGTM

**Review by tarukumar — APPROVED** [review]
LGTM

**Review by lugi0 — APPROVED** [review]
lgtm

**Pull request merged**
