### PR TITLE
Add test for verifiying alert severity

### PR DESCRIPTION
**Pull request by lucferbux**
Jenkins job: https://opendatascience-jenkins-csb-rhods.apps.ocp-c1.prod.psi.redhat.com/job/rhods-ci-pr-test/487

### CODE REVIEW

**Review by jgarciao — COMMENTED** [review]
This looks good. Please, check it with jenkins (adding here the link to the job) and add the labels "new test" and "verified" if the test passed successfully

**Comment by jgarciao** [comment]
New jenkins job using LiveBuild: https://opendatascience-jenkins-csb-rhods.apps.ocp-c1.prod.psi.redhat.com/job/rhods-ci-pr-test/487
`Verify All Alerts Are Critical :: Verifies that, in a regular situ... | PASS |`

**Review by jgarciao — APPROVED** [review]
lgtm

**Review by bdattoma — APPROVED** [review]
lgtm

**Pull request merged**
