### PR TITLE
Added status check for enable button in ACE

### PR DESCRIPTION
**Pull request by tarukumar**
we have observed that while doing smoke/sanity testing Script fails if ACE is enabled previously, to handle that have added condition to check if it is not have enable button in Explore page to check in Enabled page if respective tile is present or not and failed the overall Test suite

Signed-off-by: tarukumar <takumar@redhat.com>

### CODE REVIEW

**Comment by vasukulkarni** [comment]
please take help from Arthy and run PR test job on this one.

**Comment by tarukumar** [comment]
> please take help from Arthy and run PR test job on this one.

**Comment by tarukumar** [comment]
> please take help from Arthy and run PR test job on this one.

Done.

**Comment by bdattoma** [comment]
@tarukumar why did you create the keyword "Verify Service Is Available In The Enabled Page" when "Verify Service Is Enabled" already is in place and seems to perform the same actions?

**Comment by tarukumar** [comment]
> @tarukumar why did you create the keyword "Verify Service Is Available In The Enabled Page" when "Verify Service Is Enabled" already is in place and seems to perform the same actions?

@bdattoma I understand it does the same work ..i just wanted to make sure when the "enabled" button is not available in explore tab it should definitely present in Enabled tab. I could handle it with warning and pass the whole Test suite but keeping the TC scope in mind . I think it's better to have the proper log information to user for better understanding.

**Comment by tarukumar** [comment]
AHhh..got it ..Removed the duplicate keyword ..
New Changes has been verified [Jobid-146](https://opendatascience-jenkins-csb-rhods.apps.ocp-c1.prod.psi.redhat.com/job/rhods-ci-pr-test/146/) and working as expected

**Comment by bdattoma** [comment]
> AHhh..got it ..Removed the duplicate keyword .. New Changes has been verified [Jobid-146](https://opendatascience-jenkins-csb-rhods.apps.ocp-c1.prod.psi.redhat.com/job/rhods-ci-pr-test/146/) and working as expected

okay good. I think it would be necessary to launch a PR test job to run all the TCs (i.e., without setting this param: --extra-robot-args '-t *Anaconda* ')

**Comment by tarukumar** [comment]
> > AHhh..got it ..Removed the duplicate keyword .. New Changes has been verified [Jobid-146](https://opendatascience-jenkins-csb-rhods.apps.ocp-c1.prod.psi.redhat.com/job/rhods-ci-pr-test/146/) and working as expected
> 
> okay good. I think it would be necessary to launch a PR test job to run all the TCs (i.e., without setting this param: --extra-robot-args '-t _Anaconda_ ')

Its done [PR-147](https://opendatascience-jenkins-csb-rhods.apps.ocp-c1.prod.psi.redhat.com/job/rhods-ci-pr-test/147) for reference. Do we really need to test in all test cases in PR CI.I understand why we are testing all the TCs..to check dependency and etc. If i understand the purpose of testing PR is to not push the broken code or buggy code to master if we text a respective PR also it does the same in background. Correct me if my understanding is wrong . Thank you

**Comment by bdattoma** [comment]
> > > AHhh..got it ..Removed the duplicate keyword .. New Changes has been verified [Jobid-146](https://opendatascience-jenkins-csb-rhods.apps.ocp-c1.prod.psi.redhat.com/job/rhods-ci-pr-test/146/) and working as expected
> > 
> > 
> > okay good. I think it would be necessary to launch a PR test job to run all the TCs (i.e., without setting this param: --extra-robot-args '-t _Anaconda_ ')
> 
> It's done [PR-147](https://opendatascience-jenkins-csb-rhods.apps.ocp-c1.prod.psi.redhat.com/job/rhods-ci-pr-test/147) for reference.

ok cool. I would also run the PRtest in the opposite scenario, so when the keyword is expected to success.

**Comment by tarukumar** [comment]
> > > > AHhh..got it ..Removed the duplicate keyword .. New Changes has been verified [Jobid-146](https://opendatascience-jenkins-csb-rhods.apps.ocp-c1.prod.psi.redhat.com/job/rhods-ci-pr-test/146/) and working as expected
> > > 
> > > 
> > > okay good. I think it would be necessary to launch a PR test job to run all the TCs (i.e., without setting this param: --extra-robot-args '-t _Anaconda_ ')
> > 
> > 
> > It's done [PR-147](https://opendatascience-jenkins-csb-rhods.apps.ocp-c1.prod.psi.redhat.com/job/rhods-ci-pr-test/147) for reference.
> 
> ok cool. I would also run the PRtest in the opposite scenario, so when the keyword is expected to success.

@bdattoma  Verified the opposite scenario [PR-153 ](https://opendatascience-jenkins-csb-rhods.apps.ocp-c1.prod.psi.redhat.com/job/rhods-ci-pr-test/153/)

**Review by bdattoma — APPROVED** [review]

**Review by vasukulkarni — APPROVED** [review]

**Pull request merged**
