### PR TITLE
Update expected CUDA version to 11.7

### PR DESCRIPTION
**Pull request by lugi0**
Signed-off-by: Luca Giorgi <lgiorgi@redhat.com>

### CODE REVIEW

**Comment by lugi0** [comment]
test job: https://opendatascience-jenkins-csb-rhods.apps.ocp-c1.prod.psi.redhat.com/job/rhods-ci-pr-test/1243/console

**Comment by lugi0** [comment]
Tested here: https://opendatascience-jenkins-csb-rhods.apps.ocp-c1.prod.psi.redhat.com/job/rhods-ci-pr-test/1248/console
```
==============================================================================
Tests                                                                 | PASS |
16 tests, 16 passed, 0 failed
==============================================================================
```

**Review by pablofelix — APPROVED** [review]
/lgtm

**Review by jgarciao — APPROVED** [review]
lgtm

**Pull request merged**
