### PR TITLE
By default, disable email report

### PR DESCRIPTION
**Pull request by jgarciao**
Disables email report by default because to avoid robot tests not being run because
of missing email parameters

Thanks to @tarukumar for suggesting the fix

Signed-off-by: Jorge Garcia Oncins <jgarciao@redhat.com>

### CODE REVIEW

**Review by pablofelix — APPROVED** [review]
lgtm

**Review by tarukumar — APPROVED** [review]
LGTM

**Comment by tarukumar** [comment]
https://opendatascience-jenkins-csb-rhods.apps.ocp-c1.prod.psi.redhat.com/job/rhods-smoke/569/

**Comment by jgarciao** [comment]
Tested successfully here: https://opendatascience-jenkins-csb-rhods.apps.ocp-c1.prod.psi.redhat.com/job/rhods-smoke/569

**Pull request merged**
