### PR TITLE
Make "Get RHODS Version" a common keyword, since it was duplicated

### PR DESCRIPTION
**Pull request by manosnoam**
The keyword "Get RHODS Version" is defined twice.
It should be a common keyword, otherewise it may cause conflicts:

```
Rhods Olm :: Perform and verify RHODS OLM tasks                               
Can Install RHODS Operator  Cluster type: selfmanaged
Verifying RHODS installation
...
| FAIL |
Multiple keywords with name 'Get RHODS Version' found. 
Give the full name of the keyword you want to use:
    InstalledOperators.Get RHODS version
    oc_version.Get RHODS Version
```
Signed-off-by: manosnoam <nmanos@redhat.com>

### CODE REVIEW

**Comment by manosnoam** [comment]
You can see in this build why this PR is required:
https://opendatascience-jenkins-csb-rhods.apps.ocp-c1.prod.psi.redhat.com/job/rhods-ci-pr-test/1849/console

```
Verified redhat-ods-monitoring
| FAIL |
Multiple keywords with name 'Get RHODS Version' found. Give the full name of the keyword you want to use:
    InstalledOperators.Get RHODS version
    oc_version.Get RHODS Version
```

**Comment by jgarciao** [comment]
Adding the "do not merge" label until we discuss in the automation meeting about this

**Comment by manosnoam** [comment]
We're getting this error also in smoke test now:
https://opendatascience-jenkins-csb-rhods.apps.ocp-c1.prod.psi.redhat.com/job/rhods-smoke/2647/console
fyi @nehachopra27

I'm increasing priority for this fix.

**Review by bdattoma — APPROVED** [review]

**Comment by jgarciao** [comment]
Merging the PR after discussing it in slack, as the smoke test was failing

**Pull request merged**
