### PR TITLE
Remove workaround for resolved product bugs RHOAIENG-2724, RHOAIENG-2869

### PR DESCRIPTION
**Pull request by manosnoam**
These RHOAI bugs were recently resolved:
- https://issues.redhat.com/browse/RHOAIENG-2869
- https://issues.redhat.com/browse/RHOAIENG-2724

Thus removing the ProductBug tag and workaround.

image

### CODE REVIEW

**Review by jstourac — APPROVED** [review]

**Review by FedeAlonso — APPROVED** [review]

**Comment by jstourac** [comment]
Hi @manosnoam, have you tested this also with RHOAI 2.8? Shall we backport this to `releases/2.8.0` branch?

**Comment by manosnoam** [comment]
No, I haven't tested it with 2.8

**Comment by jstourac** [comment]
Okay, I have checked this briefly on my cluster where I installed 2.8. The test is very unstable without this workaround for me (failed 3 times out of 4). As such, I'm not gonna include this into the backport branch for the `releases/2.8.0`.

**Comment by manosnoam** [comment]
> Okay, I have checked this briefly on my cluster where I installed 2.8. The test is very unstable without this workaround for me (failed 3 times out of 4). As such, I'm not gonna include this into the backport branch for the `releases/2.8.0`.

hmm, if it is still unstable I guess we should reopen the bug :( 
Can you add the screenshot/details in the bug ?

**Pull request merged**
