### PR TITLE
RHOAIENG-7181 Check DW Components are Enabled by Default

### PR DESCRIPTION
**Pull request by asanzgom**
This is a Test Case meant to check that DW Components are enabled by default on DSC RHOAIENG-7181

### CODE REVIEW

**Comment by asanzgom** [comment]
Triggered rhods-ci-pr-test/2902/

**Comment by asanzgom** [comment]
job rhods-ci-pr-test/2907 passed successfully

**Review by CFSNM — APPROVED** [review]
LGTM

**Comment by asanzgom** [comment]
> LGTM, do we want to backport to releases/2.9.0 branch?

The fix is on 2.10 downstream, to run this Test Case against Release Candidate

**Review by jstourac — APPROVED** [review]

**Pull request merged**
