### PR TITLE
Removed self-managed installer support and added support to install RHODS from Operatorhub

### PR DESCRIPTION
**Pull request by tarukumar**
This PR make following changes to support below:
Removed support for self-managed installer. 
Added variable based on SM and operatorhub install for self-managed
Added support to install and uninstall  for self-manged rhods cluster using olminstall repo
Modified install verification keyword

For now you can run :
sh run_robot_test.sh --include install --test-variable image_url: --test-variable RHODS_OSD_INSTALL_REPO: <OLm repo> --test-variable cluster_type:managed --test-variable TEST_ENV:GCP --test-case tasks/Tasks/rhods_olm.robot

uninstall:

sh run_robot_test.sh --include uninstall --test-variable RHODS_OSD_INSTALL_REPO: --test-variable cluster_type:managed --test-case tasks/Tasks/rhods_olm.robot

### CODE REVIEW

**Comment by tarukumar** [comment]
Install:
`Installing RHODS operator in selfmanaged
.Verifying RHODS installation
pod operator created
pods rhods-dashboard created
pods notebook-controller created
pods odh-notebook-controller created
Verified redhat-ods-applications
Verified redhat-ods-operator
Verified redhat-ods-monitoring
RHODS has been installed
Can Install RHODS Operator                                            | PASS |
------------------------------------------------------------------------------
Rhods Olm :: Perform and verify RHODS OLM tasks                       | PASS |
1 task, 1 passed, 0 failed
==============================================================================
Output:  /home/takumar/Development/ods-ci/test-output/ods-ci-2023-01-19-13-29-dhvANce0gh/output.xml
XUnit:   /home/takumar/Development/ods-ci/test-output/ods-ci-2023-01-19-13-29-dhvANce0gh/xunit_test_result.xml
Log:     /home/takumar/Development/ods-ci/test-output/ods-ci-2023-01-19-13-29-dhvANce0gh/log.html
Report:  /home/takumar/Development/ods-ci/test-output/ods-ci-2023-01-19-13-29-dhvANce0gh/test_report.html
`


Uninstall:

`Uninstalling RHODS operator in selfmanaged
Removing RHODS... Be patient...
kfdef.kfdef.apps.kubeflow.org "rhods-notebooks" deleted
kfdef.kfdef.apps.kubeflow.org "modelmesh-monitoring" deleted
kfdef.kfdef.apps.kubeflow.org "monitoring" deleted
kfdef.kfdef.apps.kubeflow.org "rhods-anaconda" deleted
kfdef.kfdef.apps.kubeflow.org "rhods-dashboard" deleted
kfdef.kfdef.apps.kubeflow.org "rhods-model-mesh" deleted
kfdef.kfdef.apps.kubeflow.org "rhods-nbc" deleted
namespace "rhods-notebooks" deleted
namespace "redhat-ods-monitoring" deleted
namespace "redhat-ods-applications" deleted
namespace "redhat-ods-operator" deleted
customresourcedefinition.apiextensions.k8s.io "kfdefs.kfdef.apps.kubeflow.org" deleted
.redhat-ods-monitoring deleted
redhat-ods-applications deleted
redhat-ods-operator deleted
RHODS has been uninstalled
Can Uninstall RHODS Operator                                          | PASS |
------------------------------------------------------------------------------
Rhods Olm :: Perform and verify RHODS OLM tasks                       | PASS |
1 task, 1 passed, 0 failed
==============================================================================
Output:  /home/takumar/Development/ods-ci/test-output/ods-ci-2023-01-19-13-22-yMJsvLJkA7/output.xml
XUnit:   /home/takumar/Development/ods-ci/test-output/ods-ci-2023-01-19-13-22-yMJsvLJkA7/xunit_test_result.xml
Log:     /home/takumar/Development/ods-ci/test-output/ods-ci-2023-01-19-13-22-yMJsvLJkA7/log.html
Report:  /home/takumar/Development/ods-ci/test-output/ods-ci-2023-01-19-13-22-yMJsvLJkA7/test_report.html
`

**Comment by tarukumar** [comment]
image

**Review by pablofelix — APPROVED** [review]
/lgtm

**Review by aloganat — APPROVED** [review]
lgtm

**Review by mwaykole — APPROVED** [review]

**Pull request merged**
