### PR TITLE
In RHOSi Setup and Teardown, warn if alerts are firing or pending

### PR DESCRIPTION
**Pull request by jgarciao**
In RHOSi Setup and RHOSi Teardown, add a warning to the Robot Framework log if any alert except for DeadManSnitch is firing 

Signed-off-by: Jorge Garcia Oncins <jgarciao@redhat.com>

### CODE REVIEW

**Comment by jgarciao** [comment]
Being tested here: https://opendatascience-jenkins-csb-rhods.apps.ocp-c1.prod.psi.redhat.com/job/rhods-ci-pr-test/1392

**Review by bdattoma — DISMISSED** [review]

**Comment by jgarciao** [comment]
Testes successfully here:
- Without alerts: https://opendatascience-jenkins-csb-rhods.apps.ocp-c1.prod.psi.redhat.com/job/rhods-ci-pr-test/1428
- With alerts: https://opendatascience-jenkins-csb-rhods.apps.ocp-c1.prod.psi.redhat.com/job/rhods-ci-pr-test/1429

**Comment by jgarciao** [comment]
Tested successfully (see the warnings at the top for the second scenario):
- [Without any alert firing/pending](https://opendatascience-jenkins-csb-rhods.apps.ocp-c1.prod.psi.redhat.com/job/rhods-ci-pr-test/1432/TestReport/)
- [With some alerts firing/pending ](https://opendatascience-jenkins-csb-rhods.apps.ocp-c1.prod.psi.redhat.com/job/rhods-ci-pr-test/1431/TestReport/)

**Comment by jgarciao** [comment]
> do you know if this adds running time and if so how much?

I created a new keyword to avoid that. It adds less than a second to ROSi Setup/teardown

image

**Review by tarukumar — APPROVED** [review]

**Pull request merged**
