### PR TITLE
Backport DW UI Upgrade tests to 2.10

### PR DESCRIPTION
**Pull request by ChughShilpa**
Supported codeflare-sdk version for 2.10 release is "v0.16.1"

### CODE REVIEW

**Comment by ChughShilpa** [comment]
Tested pre-upgrade DW UI tests on 2.10 cluster - rhoai-test-flow/236/console

**Comment by sutaakar** [comment]
Test fails for me with: `'Requested by test-ns-rayupgrade: 2.794 GiB' does not match 'Requested by test-ns-rayupgrade: 2861.023 GiB'`

**Comment by ChughShilpa** [comment]
> Test fails for me with: `'Requested by test-ns-rayupgrade: 2.794 GiB' does not match 'Requested by test-ns-rayupgrade: 2861.023 GiB'`

Yes the test failed in Jenkins rhoai-test-flow/236/console at the same step

**Comment by Srihari1192** [comment]
> > Test fails for me with: `'Requested by test-ns-rayupgrade: 2.794 GiB' does not match 'Requested by test-ns-rayupgrade: 2861.023 GiB'`
> 
> Yes the test failed in Jenkins rhoai-test-flow/236/console at the same step

Test failures are related to invalid memory conversion and not according to latest changes for the method [Get Memory Requested ](https://github.com/red-hat-data-services/ods-ci/blob/releases/2.13.0/ods_ci/tests/Resources/Page/DistributedWorkloads/WorkloadMetricsUI.resource#L157) , updating to this changes with other workload type will fix this error as we implemented according to the resources requesting in codeflare-sdk upgrade tests  `TestMNISTRayClusterUp`
   
`${memory_requested} =   Get Memory Requested    ${PRJ_TITLE}    ${LOCAL_QUEUE_NAME}   Upgrade `

**Comment by ChughShilpa** [comment]
Pre-upgrade test passed - rhoai-test-flow/629/console

**Comment by ChughShilpa** [comment]
DW UI test passed - rhoai-test-flow/632/console

**Review by sutaakar — APPROVED** [review]

**Review by Srihari1192 — APPROVED** [review]

**Pull request merged**
