### PR TITLE
Add Training operator smoke tests to DW stack

### PR DESCRIPTION
**Pull request by sutaakar**

### CODE REVIEW

**Review by ChughShilpa — DISMISSED** [review]
lgtm 

Just one small change request, Instead of using `  %{ODH_NAMESPACE=redhat-ods-applications}`, we can use 
`${APPLICATIONS_NAMESPACE}` variable which fetches value from test variable file. Hence, our smoke tests run on ODH nightly as well as rhoai downstream .

https://github.com/red-hat-data-services/ods-ci/blob/master/ods_ci/test-variables.yml.example#L81

Currently our smoke tests fails in https://opendatascience-jenkins-csb-rhods.apps.ocp-c1.prod.psi.redhat.com/job/odh/job/autotrigger-smoke/

**Comment by sutaakar** [comment]
@ChughShilpa thanks, good catch
should be fixed now

**Comment by sutaakar** [comment]
This needs to be fixed in other files too, though it is out of scope for this PR.

**Review by ChughShilpa — APPROVED** [review]

**Comment by ChughShilpa** [comment]
> @ChughShilpa thanks, good catch should be fixed now

Thanks Karel

**Comment by ChughShilpa** [comment]
> This needs to be fixed in other files too, though it is out of scope for this PR.

Yes right, i will raise the PR for this

**Review by jiripetrlik — APPROVED** [review]

**Pull request merged**
