### PR TITLE
Add "Clean Up User Notebook" keyword

### PR DESCRIPTION
**Pull request by jgarciao**
This keyword deletes all files and folders in a user's notebook PVC (excluding hidden files and folders).

It will be useful to fix test teardown in ODS-517 in PR #102, as regular "Clean Up Server" fails
to do the job because the PVC is full for that test.

Signed-off-by: Jorge Garcia Oncins <jgarciao@redhat.com>

### CODE REVIEW

**Comment by vasukulkarni** [comment]
:+1:

**Comment by lugi0** [comment]
Looks good to me, just a bit scared about the `find` command :)

**Review by lugi0 — COMMENTED** [review]
Looks good to me, just a bit scared about the `find` command :)

**Comment by jgarciao** [comment]
Tested here: https://opendatascience-jenkins-csb-rhods.apps.ocp-c1.prod.psi.redhat.com/job/rhods-ci-pr-test/141/
3 JupyterHub tests failed for not related reasons

About the find command, I think it's safe (the list of deleted files is written in the log) but  as it is a new keyword I was thinking of using it initially only in test ODS-517. If it works well in the future maybe we can use it in Common.End Web Test

**Review by bdattoma — COMMENTED** [review]
looks good to me too

**Review by vasukulkarni — APPROVED** [review]

**Pull request merged**
