### PR TITLE
Patternfly changes for gpu model serving

### PR DESCRIPTION
**Pull request by tarukumar**

### CODE REVIEW

**Comment by tarukumar** [comment]
#smoke : 4339

**Comment by mwaykole** [comment]
can u plz rebase the patch

**Review by mwaykole — APPROVED** [review]

**Review by jstourac — COMMENTED** [review]
LGTM, thank you.

One question - there are attempts to not to use the `pf-v5` prefix as this may change due to the PatternFly version in the future again. Instead, something like `contains(@class,"-table__action")` is preferred, see e.g. #1117. WDYT?

**Comment by tarukumar** [comment]
@jstourac for now i will keep this and will send another pr which i am working on to have this fix. For now i need this pr to be merged to handle the other pr

**Review by jstourac — APPROVED** [review]

**Pull request merged**
