### PR TITLE
Remove workaround for DS Project creation RHODS-8477

### PR DESCRIPTION
**Pull request by bdattoma**
In RHODS 1.28 the issue with user not being redirected to DS Project page has been fixed. Hence, it's worth to remove the workaround in the code (even if it was conditional)

### CODE REVIEW

**Comment by bdattoma** [comment]
test against 1.28: [1881](https://opendatascience-jenkins-csb-rhods.apps.ocp-c1.prod.psi.redhat.com/job/rhods-ci-pr-test/1881/console) _RUNNING_

**Comment by lugi0** [comment]
I'm ok with the change, but are we absolutely sure the issue has been fixed and won't appear ever again?
If it's possible we'll encounter it in the future, IMHO it'd be worth it to leave the conditional workaround in, with a Log message explicitly stating that the issue has reappeared if it's ever executed

**Comment by bdattoma** [comment]
> I'm ok with the change, but are we absolutely sure the issue has been fixed and won't appear ever again? If it's possible we'll encounter it in the future, IMHO it'd be worth it to leave the conditional workaround in, with a Log message explicitly stating that the issue has reappeared if it's ever executed

the workaround was already conditional, but I fear like from now to 5 releases we'll stop looking for the warning and a possible regression would slip in with higher probability. That's the reason why I thought to remove it at all

**Comment by lugi0** [comment]
We could force a failure in case the conditional block is entered to make sure it won't get missed

**Review by mwaykole — APPROVED** [review]

**Comment by bdattoma** [comment]
new jenkins test after latest changes: [1884](https://opendatascience-jenkins-csb-rhods.apps.ocp-c1.prod.psi.redhat.com/job/rhods-ci-pr-test/1884/TestReport/) _OK_ there are 2 failures: 1 is expected because there were other DS projects in the cluster for manual testing reasons. 1 happened for a delay in loading the web page (loading spinner can be seen in the screenshot)

**Review by jgarciao — APPROVED** [review]

**Review by nehachopra27 — APPROVED** [review]
LGTM

**Pull request merged**
