### PR TITLE
Improve keyword to wait for dashboard and remove Seldon folder

### PR DESCRIPTION
**Pull request by bdattoma**
we've notice some rare failures in waiting until the dashboard is loaded (the RHODS log was loaded but the rest of the page like cards were not).

The PR is adding 2 fixes:
1. Wait until the expected page title (h1) is loaded, e.g., Explore.
2. Wait until the applications' cards are loaded - OPTIONAL

### CODE REVIEW

**Review by lugi0 — APPROVED** [review]

**Review by jgarciao — APPROVED** [review]
lgtm

**Comment by bdattoma** [comment]
Jenkins Job 1: testing through ODS-293, ODS-262 and ODS-248 [1447](https://opendatascience-jenkins-csb-rhods.apps.ocp-c1.prod.psi.redhat.com/job/rhods-ci-pr-test/1447/console) _RUNNING_

Jenkins Job 2: testing through DS Projects suite: soon...

**Review by lugi0 — APPROVED** [review]

**Review by jgarciao — DISMISSED** [review]
lgtm

**Review by lugi0 — APPROVED** [review]

**Review by jgarciao — APPROVED** [review]
lgtm

**Pull request merged**
