### PR TITLE
Add option to skip 'Maybe Wait For Dashboard Loading Spinner Page' for performance testing

### PR DESCRIPTION
**Pull request by kpouget**
Following the discussion in #709 I open this PR to discuss how to get this change merged in the code, in a way that is compatible with the notebook scale test and QE tests at the same time.

The reason why we can't have it as part of the notebook scale test is that this call introduce a `Sleep 5s` delay that invalidates the timing measurements.

### CODE REVIEW

**Comment by bdattoma** [comment]
Jenkins Jobs:
- DS Project suites against RHODS v1.25: [1671](https://opendatascience-jenkins-csb-rhods.apps.ocp-c1.prod.psi.redhat.com/job/rhods-ci-pr-test/1671/) _RUNNING_

**Comment by kpouget** [comment]
@bdattoma I have updated the PR as discussed offline.
The new behavior is that by default, nothing is changed. 
but if this is defined:
```
${ODH_DASHBOARD_DO_NOT_WAIT_FOR_SPINNER_PAGE}  ${true}
```
then the wait for the spinner is skipped.

**Comment by bdattoma** [comment]
Jenkins Job (installing latest 1.25 version and run DS Project test): [1704](https://opendatascience-jenkins-csb-rhods.apps.ocp-c1.prod.psi.redhat.com/job/rhods-ci-pr-test/1704/console) _RUNNING_

**Review by tarukumar — APPROVED** [review]
/lgtm

**Pull request merged**
