### PR TITLE
Fix keyword conflict for post-install

### PR DESCRIPTION
**Pull request by lugi0**
Signed-off-by: Luca Giorgi <lgiorgi@redhat.com>

### CODE REVIEW

**Review by jgarciao — DISMISSED** [review]
lgtm

**Review by tarukumar — DISMISSED** [review]
LGTM

**Comment by lugi0** [comment]
Can be merged now

**Review by bdattoma — APPROVED** [review]
lgtm

**Review by jgarciao — APPROVED** [review]
lgtm

**Pull request merged**
