### PR TITLE
Add test case for backend and ui of PVC change

### PR DESCRIPTION
**Pull request by tarukumar**
Closing the older PR(https://github.com/red-hat-data-services/ods-ci/pull/241) and opened a new one

Signed-off-by: tarukumar <takumar@redhat.com>

### CODE REVIEW

**Comment by tarukumar** [comment]
https://opendatascience-jenkins-csb-rhods.apps.ocp-c1.prod.psi.redhat.com/job/rhods-ci-pr-test/560

**Review by bdattoma — DISMISSED** [review]
lgmt

**Comment by jgarciao** [comment]
`Verify User Cannot Set An Unsupported PVC Size Using Backend ` failed because of an error in `Clean Up Server` that now is fixed on master. Would you mind rebasing to master and running the test again?

**Review by jgarciao — APPROVED** [review]
lgtm

**Review by bdattoma — APPROVED** [review]

**Review by jgarciao — APPROVED** [review]
lgtm

**Pull request merged**
