### PR TITLE
Update codeflare-sdk tests to run against latest release tag

### PR DESCRIPTION
**Pull request by Srihari1192**
closes https://issues.redhat.com/browse/RHOAIENG-5070

### CODE REVIEW

**Review by sutaakar — APPROVED** [review]

**Review by ChughShilpa — APPROVED** [review]
lgtm

**Review by jiripetrlik — APPROVED** [review]

**Comment by sutaakar** [comment]
Makes me think, is there a need to work with Git at all? Why not to install latest version directly from pip?

**Comment by Srihari1192** [comment]
> Makes me think, is there a need to work with Git at all? Why not to install latest version directly from pip?

Yes we can install either way , but for test execution we need the respective repo branch aswell

**Comment by sutaakar** [comment]
ok, fine for me

**Pull request merged**
