### PR TITLE
Upgrade to RF 5

### PR DESCRIPTION
**Pull request by lugi0**
Signed-off-by: Luca Giorgi <lgiorgi@redhat.com>

### CODE REVIEW

**Comment by lugi0** [comment]
Smoke job: https://opendatascience-jenkins-csb-rhods.apps.ocp-c1.prod.psi.redhat.com/job/rhods-ci-pr-test/1450/console

**Comment by lugi0** [comment]
Job failed, seems like the jenkins node is using python 3.6 and cannot fetch the correct selenium version

**Comment by lugi0** [comment]
https://opendatascience-jenkins-csb-rhods.apps.ocp-c1.prod.psi.redhat.com/job/rhods-ci-pr-test/1460/console

**Comment by lugi0** [comment]
Sanity: https://opendatascience-jenkins-csb-rhods.apps.ocp-c1.prod.psi.redhat.com/job/rhods-ci-pr-test/1463/console

**Comment by mwaykole** [comment]
hey @lugi0  i think in rp5 we have some changes with `return` also may be u can  search and replace it (u can ignore it just a suggestion )

**Review by mwaykole — APPROVED** [review]

**Comment by lugi0** [comment]
@mwaykole the return change is not even a deprecation warning at this point, I think we can wait before implementing the change

**Review by jgarciao — DISMISSED** [review]
lgtm

**Review by tarukumar — APPROVED** [review]
lgtm

**Review by jgarciao — APPROVED** [review]

**Pull request merged**
