### PR TITLE
Move pytorch job Training tests from Tier1 to Sanity tag

### PR DESCRIPTION
**Pull request by ChughShilpa**
Closes [RHOAIENG-16556](https://issues.redhat.com/browse/RHOAIENG-16556)

### CODE REVIEW

**Comment by sutaakar** [comment]
These tests need GPU.
Is GPU available for sanity tests?

**Comment by aloganat** [comment]
Please add the tag "GeneralPurpose-GPU" in the test script. So, that the test will get executed in GPU run executions.

**Comment by bdattoma** [comment]
> Please add the tag "GeneralPurpose-GPU" in the test script. So, that the test will get executed in GPU run executions.

we don't have this tag in ODS-CI. Let's talk offline

**Comment by ChughShilpa** [comment]
As discussed with @bdattoma, it is recommended to exclude GPU tests by default from Sanity jobs, there are no changes in the code yet, but from few releases Sanity is running without GPUs
Hence, closing this PR.

**Comment by ChughShilpa** [comment]
As discussed with @bdattoma, it is recommended to exclude GPU tests by default from Sanity jobs, there are no changes in the code yet, but from few releases Sanity is running without GPUs
Hence, closing this PR.

**Pull request closed without merging**
