### PR TITLE
Add tests to verify git plugin is installed(ODS-452)

### PR DESCRIPTION
**Pull request by prudhvi-165**
Signed-off-by: prudhvi <pnammi@redhat.com>

### CODE REVIEW

**Comment by prudhvi-165** [comment]
Jenkins Link: https://opendatascience-jenkins-csb-rhods.apps.ocp-c1.prod.psi.redhat.com/job/rhods-ci-pr-test/555/
Result: Passed

**Review by jgarciao — COMMENTED** [review]
I believe this is already tested in tests/Tests/500__jupyterhub/plugin-verification.robot  but @tarukumar  might be able to confirm it

Additionally, until we have a clear policy about Sanity/Tier1 tags I think Sanity should be added too as tag

**Comment by prudhvi-165** [comment]
Sanity  is added as a force tag on Line 12  `Force Tags          Smoke    Sanity    JupyterHub` , Shall I add it again?

**Comment by prudhvi-165** [comment]
> I believe this is already tested in tests/Tests/500__jupyterhub/plugin-verification.robot but @tarukumar might be able to confirm it
> 
> Additionally, until we have a clear policy about Sanity/Tier1 tags I think Sanity should be added too as tag

Sanity is added as a force tag on Line 12 Force Tags Smoke Sanity JupyterHub , Shall I add it again?

**Comment by jgarciao** [comment]
>Sanity is added as a force tag on Line 12 Force Tags Smoke Sanity JupyterHub , Shall I add it again?
Sorry, I didn't see it. I personally don't like Force Tags very much but no need to add it if all tests in the test suite follow this pattern

**Comment by lugi0** [comment]
This has already been automated in https://github.com/red-hat-data-services/ods-ci/pull/256

**Comment by milindw96** [comment]
> This has already been automated in #256

if it's already automated then @prudhvi-165  can u close it,  @lugi0  can u please share your thoughts on it?

**Comment by lugi0** [comment]
+1 @milindw96 , I think this should be closed

**Pull request closed without merging**
