### PR TITLE
Add generate resources documentation

### PR DESCRIPTION
**Pull request by pablofelix**
Add generate resources documentation

### CODE REVIEW

**Comment by LaVLaS** [comment]
@pablofelix Is this an automated way of adding documentation for each documentation item?

**Comment by pablofelix** [comment]
Yes, currently it looks for files in Resources/Page folder,  extracts the existing keywords arguments and documentation items from each file using libdoc, and  generates a doc file in docs/keywords for each file. It could be extended easily for tests documentation.

**Comment by pablofelix** [comment]
PR has been signed off

**Comment by bdattoma** [comment]
@pablofelix what's the status of this PR?

**Comment by aloganat** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
