### PR TITLE
Use Addon CatalogSource from openshift-marketplace

### PR DESCRIPTION
**Pull request by winklerm**
The RHODS addon CatalogSource has moved to the openshift-marketplace namespace [1].

[1] https://gitlab.cee.redhat.com/data-hub/olminstall/-/merge_requests/30/

### CODE REVIEW

**Comment by winklerm** [comment]
Depends on https://gitlab.cee.redhat.com/data-hub/olminstall/-/merge_requests/30/

**Comment by winklerm** [comment]
The https://gitlab.cee.redhat.com/data-hub/olminstall/-/merge_requests/30/ has been merged, please review, thanks!

**Comment by tarukumar** [comment]
@winklerm could you run this pr for verification of v1 and v2 operator to make sure everything is working fine with new changes

**Review by jgarciao — APPROVED** [review]

**Review by bdattoma — APPROVED** [review]

**Comment by tarukumar** [comment]
I have run the Jenkins job for verification : smoke job : #3348,#3349#3350#3351

**Comment by winklerm** [comment]
@tarukumar Thank you! I have run the operator v2 DW smoke job for verification: https://opendatascience-jenkins-csb-rhods.apps.ocp-c1.prod.psi.redhat.com/view/Distributed_Workloads_Jobs/job/rhods-dw-smoke-new-operator/lastCompletedBuild/, the one failure is unrelated (other tests passed, so the deployment worked).

**Pull request merged**
