### PR TITLE
Fix: 2.6 xpath fixes

### PR DESCRIPTION
**Pull request by FedeAlonso**
Fix for tests:
ODS-1775 : Verify User Can Create A Data Science Project
ODS-1814: Verify User Can Create And Start A Workbench With Existent PV Storage
ODS-1818: Verify Users Can Start, Stop, Launch And Delete A Workbench
ODS-1813: Verify Users Can Start, Stop And Launch A Workbench From DS Projects Home Page

### CODE REVIEW

**Review by bdattoma — DISMISSED** [review]

**Comment by FedeAlonso** [comment]
Execution of the 5 tests
image

**Review by jiridanek — APPROVED** [review]

**Comment by jiridanek** [comment]
(don't forget to squash, then merge)

**Review by jstourac — APPROVED** [review]
LGTM, as Jiri mentioned - don't forget to squash the commits with the merge :slightly_smiling_face:

**Comment by jstourac** [comment]
Not merging since it has a `don't merge` label ( why don't we use draft feature :thinking: ).

**Comment by FedeAlonso** [comment]
> Not merging since it has a `don't merge` label ( why don't we use draft feature 🤔 ).

I  did both (draft + don't merge) and forget to delete the label.
Thanks for noticing @jstourac

**Pull request merged**
