### PR TITLE
Change `IBM Watson Studio` to `IBM watsonx.ai` title in 2.9+

### PR DESCRIPTION
**Pull request by jstourac**
https://issues.redhat.com/browse/RHOAIENG-4447

----

Tested locally:

Screenshot from 2024-04-11 09-44-04

### CODE REVIEW

**Review by jiridanek — APPROVED** [review]

**Review by manosnoam — APPROVED** [review]

**Comment by manosnoam** [comment]
@jstourac Note that we might also need to update it to "IBM watsonx.ai" in ods_ci/tests/Resources/Files/AppsInfoDictionary_latest.json

**Comment by bdattoma** [comment]
> @jstourac Note that we might also need to update it to "IBM watsonx.ai" in ods_ci/tests/Resources/Files/AppsInfoDictionary_latest.json

yes! this would complete the fix. Tests like ODS-488 rely on that JSON file

**Comment by jstourac** [comment]
Thanks, will look into that file and update this PR.

**Comment by jstourac** [comment]
Right, there are more things to fix in the extra tier tests - I'm gonna merge this now and will provide a followup PR instead in the end. Thank you, guys!

**Pull request merged**
