### PR TITLE
Bump jupyterlibrary to ^0.4.0

### PR DESCRIPTION
**Pull request by lugi0**

### CODE REVIEW

**Review by bdattoma — DISMISSED** [review]

**Comment by kpouget** [comment]
thanks @lugi0, trying it now in my scale test environment

**Comment by kpouget** [comment]
I confirm that [this works](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/668/pull-ci-openshift-psap-ci-artifacts-main-ods-plot-notebooks/1644263366778163200/artifacts/plot-notebooks/test/artifacts/report_00_report:_error_report.html) for me :)

**Review by jgarciao — APPROVED** [review]
lgtm

**Comment by lugi0** [comment]
@kpouget this has been merged and updated again since you last tested it to include a version bump for the robocop tool. I suggest updating the lock file in your environment again to be in sync with us.

**Pull request merged**
