### PR TITLE
Update ODS-488 to remove perceptilabs check for Jupyter (instead of JupyterHub)

### PR DESCRIPTION
**Pull request by bdattoma**
RHODS v1.16 is going to remove Perceptilabs from the applications in "Explore" page. This PR applies the necessary change for ODS-488

It also include a fix for ODS-488 to account new Jupyter tile.

Signed-off-by: bdattoma <bdattoma@redhat.com>

### CODE REVIEW

**Comment by bdattoma** [comment]
Tested on jenkins [job#1203](https://opendatascience-jenkins-csb-rhods.apps.ocp-c1.prod.psi.redhat.com/job/rhods-ci-pr-test/1203/TestReport/) _SUCCESS_

**Comment by mwaykole** [comment]
please resolve the conflicts

**Review by mwaykole — APPROVED** [review]
LGTM

**Review by lugi0 — APPROVED** [review]

**Review by jgarciao — APPROVED** [review]
lgtm

**Pull request merged**
